version: '3.9'

x-airflow-common:
  &airflow-common
  build: ./airflow
  user: "${AIRFLOW_UID:-50000}:0"
  environment:
    &airflow-common-env
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-repo:5432/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    AIRFLOW__CORE__LAZY_LOAD_PLUGINS: 'false'
    AIRFLOW__CORE__MAX_MAP_LENGTH: 4000
    _AIRFLOW_DB_MIGRATE: 'true'
    AIRFLOW__CORE__TEST_CONNECTION: Enabled

    FRANCETRAVAIL_HOST: ${FRANCETRAVAIL_HOST}
    FRANCETRAVAIL_ID_CLIENT: ${FRANCETRAVAIL_ID_CLIENT}
    FRANCETRAVAIL_CLE_SECRETE: ${FRANCETRAVAIL_CLE_SECRETE}

  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/logs:/opt/airflow/logs
  networks:
      - data-emploi

services:

  airflow-repo:
    image: postgres:15.2
    container_name: airflow-repo
    environment:      
      POSTGRES_USER : airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB : airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - data-emploi

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    image: airflow-scheduler
    command: scheduler
    environment:
      <<: *airflow-common-env
    depends_on:
      - airflow-repo

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    image: airflow-webserver
    command: webserver
    ports:
      - "8070:8080"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: 'airflow'
      _AIRFLOW_WWW_USER_PASSWORD: 'airflow'
      _AIRFLOW_WWW_USER_FIRSTNAME: 'D'
      _AIRFLOW_WWW_USER_LASTNAME: 'E'
      _AIRFLOW_WWW_USER_EMAIL: 'data.engineer.projet@gmail.com'
      _AIRFLOW_WWW_USER_ROLE: 'Admin'
    restart: always
    depends_on:
      - airflow-repo

  docker-proxy:
    image: tecnativa/docker-socket-proxy:0.1.1
    container_name: docker-proxy
    environment:
      CONTAINERS: 1
      IMAGES: 1
      AUTH: 1
      POST: 1
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - data-emploi

networks:
  data-emploi:
    name: data-emploi
    driver: bridge