transformation:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ..\stockage\entrepot.duckdb
      schema: emploi
    prod:
      type: duckdb
      path: ..\stockage\entrepot.duckdb
      schema: emploi